version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ec2-task:revision
        LoadBalancerInfo:
          ContainerName: node-app
          ContainerPort: 8080
