version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j6r0i7r3
  build:
    commands:
      - echo Building Docker image...
      - docker build -t nodejs-app-task-1 .
      - echo Pushing Docker image to ECR...
      - docker tag nodejs-app-task-1:latest public.ecr.aws/j6r0i7r3/node-app:latest
      - docker push public.ecr.aws/j6r0i7r3/node-app:latest
  post_build:
    commands:
      - echo Build completed on date
      - echo Creating image definitions file...
      - echo '[{"name":"node-app","imageUri":"public.ecr.aws/j6r0i7r3/node-app:latest","containerPort":8080}]' > imagedefinitions.json

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    imagedefinitions:
      files:
        - imagedefinitions.json
